version: "3.3"
services:
  nuxt:
    image: sda2000den/agency:0.4
    container_name: nuxt_app
    environment:
      - VIRTUAL_HOST=studioagnc.com
      - LETSENCRYPT_HOST=studioagnc.com
      - LETSENCRYPT_EMAIL=sda2000den@gmail.com
      - VIRTUAL_PORT=80

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./vhost.d:/etc/nginx/vhost.d"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./certs:/etc/nginx/certs"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
